s3_conf:
  s3_bucket: aws-rdd-bucket

sftp_conf:
  filetype: csv
  delimiter: |
  directory: /home/ubuntu/data

mongodb_config:
  database: school
  collection: students

mysql_conf:
  dbtable: testdb.TRANSACTIONSYNC
  partition_column: App_Transaction_Id
  query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"
